### ISSUE TITLE
[BUG]: Text overlapping on some dimensions

### ISSUE THREAD

**Issue by nik132-eng** [shelcia/dynamic-portfolio#260]
![image](https://user-images.githubusercontent.com/77881638/209422154-70e9cedf-4d24-48b8-a114-fbee89a5013e.png)

-> first name and last name should be in a bigger size.
-> arrange the Image in a proper manner with shadows
-> add some icons with github

**Comment by shelcia** [comment]
why last and first name needs to be bigger. There is feature to add other icons as well

**Comment by nik132-eng** [comment]
I think it will be highlight more and look more nice

**Comment by shelcia** [comment]
The changes are not necessary, but if the intro is overlapping image please treat as a bug and fix

**Comment by shelcia** [comment]
on some width dimensions, the text is overlapping image

![Screenshot 2022-12-28 at 1 00 43 PM](https://user-images.githubusercontent.com/31156685/209775482-0129d3d8-a40a-4e66-b265-70829b3e0525.png)

**Comment by chikkibum** [comment]
Hey @shelcia I would like to work on this issue.
I have tried something on developer tools and adding these snippets of code on the flex-container seems to work best.
but I couldn't figure out what files would I need to change in the codebase it seems that you are using argon design system and I am not familiar with that. I need some help regarding what files need change.


I added `justify content: space evenly; ` 


As shown in the following image the issue was that the text was overlapping with the image.

! [before](https://user-images.githubusercontent.com/71315985/215322796-db7aab19-fc0a-4105-aeec-e0e73a0ba87c.png)

after adding `justify content: space evenly;` property 

![after_justift_content](https://user-images.githubusercontent.com/71315985/215322867-ef0f91fc-a0f3-4d98-8e19-dd045cd5a986.png)

the overlapping is fixed but there is now extra space in left container.

so, I changed `margin-left: -15px; ` to `margin-left: -30px` and here is the final result:

![margin-30epx](https://user-images.githubusercontent.com/71315985/215323043-df862a5d-adcc-47a2-a2e0-cbc0b744db15.png)

Also, I have tested it on all dimensions, and it seems to fix the issue.

![phone](https://user-images.githubusercontent.com/71315985/215323160-946fa4ad-c570-4f90-86da-8b614b5014e6.png)

If I have resolved the issue, then assign me this issue so I can make a pull request.

**Comment by chikkibum** [comment]
@shelcia could you help me figuring out what files would i need to edit in order to get the desired results.

**Comment by shelcia** [comment]
@chikkibum  should be within templates folder (template 1)

**Comment by chikkibum** [comment]
@shelcia i have made the pull request.could you verify it.
